### ISSUE TITLE
Add support for Misskey 2023.10.2 and above

### ISSUE THREAD

**Issue by MomentQYC** [dev-hato/aminome#10]
This version has made major changes to the database, and executing the synchronization script will report an error
```
Traceback (most recent call last):
  File "/path/to/aminome.py", line 35, in <module>
    cur.execute('SELECT "id", "createdAt", "userId", "userHost", "channelId", "cw", "text", "tags" FROM "note" \
  File "/path/to/python3.10/dist-packages/psycopg2/extras.py", line 146, in execute
    return super().execute(query, vars)
psycopg2.errors.UndefinedColumn: column "createdAt" does not exist
LINE 1: SELECT "id", "createdAt", "userId", "userHost", "channelId",...
                     ^
```

**Comment by nakkaa** [comment]
oh, "CreatedAt" don't exist in v2023.10.2.

```
                                           Table "public.note"
          Column          |           Type            | Collation | Nullable |          Default          
--------------------------+---------------------------+-----------+----------+---------------------------
 id                       | character varying(32)     |           | not null | 
 replyId                  | character varying(32)     |           |          | 
 renoteId                 | character varying(32)     |           |          | 
 text                     | text                      |           |          | 
 name                     | character varying(256)    |           |          | 
 cw                       | character varying(512)    |           |          | 
 userId                   | character varying(32)     |           | not null | 
 localOnly                | boolean                   |           | not null | false
 renoteCount              | smallint                  |           | not null | 0
 repliesCount             | smallint                  |           | not null | 0
 reactions                | jsonb                     |           | not null | '{}'::jsonb
 visibility               | note_visibility_enum      |           | not null | 
 uri                      | character varying(512)    |           |          | 
 fileIds                  | character varying(32)[]   |           | not null | '{}'::character varying[]
 attachedFileTypes        | character varying(256)[]  |           | not null | '{}'::character varying[]
 visibleUserIds           | character varying(32)[]   |           | not null | '{}'::character varying[]
 mentions                 | character varying(32)[]   |           | not null | '{}'::character varying[]
 mentionedRemoteUsers     | text                      |           | not null | '[]'::text
 emojis                   | character varying(128)[]  |           | not null | '{}'::character varying[]
 tags                     | character varying(128)[]  |           | not null | '{}'::character varying[]
 hasPoll                  | boolean                   |           | not null | false
 userHost                 | character varying(128)    |           |          | 
 replyUserId              | character varying(32)     |           |          | 
 replyUserHost            | character varying(128)    |           |          | 
 renoteUserId             | character varying(32)     |           |          | 
 renoteUserHost           | character varying(128)    |           |          | 
 url                      | character varying(512)    |           |          | 
 channelId                | character varying(32)     |           |          | 
 threadId                 | character varying(256)    |           |          | 
 reactionAcceptance       | character varying(64)     |           |          | 
 clippedCount             | smallint                  |           | not null | '0'::smallint
 reactionAndUserPairCache | character varying(1024)[] |           | not null | '{}'::character varying[]
```

https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/core/SearchService.ts#L134

I have no good idea now in this issue.

**Comment by nakkaa** [comment]
正直、バージョンが上がるごとに仕様変更が大きすぎで、このツール(aminome)をメンテナンスしていくのが辛くなってきた。
Misskey本体に機能統合を働きかけた方が良さそう。(FirefishはMeilisearchへのインデックスを組み込み機能として提供しているし)

あるいはmisskey.ioが https://github.com/MisskeyIO/misskey-meilisearch-reindex を公開したし、開発リソースが潤沢なあちら側にお任せしたい気持ちもある。

**Comment by nakkaa** [comment]
memo: https://github.com/misskey-dev/misskey/blob/4b295088fd6b4bead05087537415b10419eee78f/packages/backend/src/misc/id/aid.ts#L34

**Comment by nakkaa** [comment]
@MomentQYC aminome supported 2023.10.2. So I close this issue.
