### ISSUE TITLE
インスタンスによっては検索できないことがある

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/aminome#7]
```
misskey7kaorg-web-1    | ERR  * [api]   Internal error occurred in notes/search: Attribute `createdAt` is not sortable. This index does not have configured sortable attributes.                                      
misskey7kaorg-web-1    | {                                                                                                                                                                                            
misskey7kaorg-web-1    |   ep: 'notes/search',                                                                                                                                                                        
misskey7kaorg-web-1    |   ps: {                                                                                                                                                                                      
misskey7kaorg-web-1    |     query: 'nakkaa',                                                                                                                                                                         
misskey7kaorg-web-1    |     userId: null,                                                                                                                                                                            
misskey7kaorg-web-1    |     limit: 10,                                                                                                                                                                               
misskey7kaorg-web-1    |     i: 'bB0JCP68qezEB8Gv',                                                                                                                                                                   
misskey7kaorg-web-1    |     offset: 0,                                                                                                                                                                               
misskey7kaorg-web-1    |     channelId: null                                                                                                                                                                          
misskey7kaorg-web-1    |   },                                                                                                                                                                                         
misskey7kaorg-web-1    |   e: {                                                                                                                                                                                       
misskey7kaorg-web-1    |     message: 'Attribute `createdAt` is not sortable. This index does not have configured sortable attributes.',                                                                              
misskey7kaorg-web-1    |     code: 'MeiliSearchApiError',                                                                                                                                                             
misskey7kaorg-web-1    |     stack: 'MeiliSearchApiError: Attribute `createdAt` is not sortable. This index does not have configured sortable attributes.\n' +                                                        
misskey7kaorg-web-1    |       '    at /misskey/node_modules/.pnpm/meilisearch@0.33.0/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:186:23\n' +                                                            
misskey7kaorg-web-1    |       '    at step (/misskey/node_modules/.pnpm/meilisearch@0.33.0/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:103:23)\n' +                                                     
misskey7kaorg-web-1    |       '    at Object.next (/misskey/node_modules/.pnpm/meilisearch@0.33.0/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:84:53)\n' +                                               
misskey7kaorg-web-1    |       '    at fulfilled (/misskey/node_modules/.pnpm/meilisearch@0.33.0/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:74:58)\n' +                                                 
misskey7kaorg-web-1    |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',                                                                                                   
misskey7kaorg-web-1    |     id: 'a0113c9c-8755-4575-85c3-37b00e64b3c6'                                                                                                                                               
misskey7kaorg-web-1    |   }                                                                                                                                                                                          
misskey7kaorg-web-1    | }                                                                                                                                                                                            
misskey7kaorg-web-1    | class_1 [MeiliSearchApiError]: Attribute `createdAt` is not sortable. This index does not have configured sortable attributes.                                                               
misskey7kaorg-web-1    |     at /misskey/node_modules/.pnpm/meilisearch@0.33.0/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:186:23                                                                        
misskey7kaorg-web-1    |     at step (/misskey/node_modules/.pnpm/meilisearch@0.33.0/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:103:23)                                                                 
misskey7kaorg-web-1    |     at Object.next (/misskey/node_modules/.pnpm/meilisearch@0.33.0/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:84:53)                                                           
misskey7kaorg-web-1    |     at fulfilled (/misskey/node_modules/.pnpm/meilisearch@0.33.0/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:74:58)                                                             
misskey7kaorg-web-1    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {                                                                                                          
misskey7kaorg-web-1    |   code: 'invalid_search_sort',                                                                                                                                                               
misskey7kaorg-web-1    |   type: 'invalid_request',
misskey7kaorg-web-1    |   link: 'https://docs.meilisearch.com/errors#invalid_search_sort',
misskey7kaorg-web-1    |   httpStatus: 400
misskey7kaorg-web-1    | } a0113c9c-8755-4575-85c3-37b00e64b3c6
```

**Comment by nakkaa** [comment]
謎

**Comment by nakkaa** [comment]
meilisearch 1.3.0, 1.1.0で発生する。
インスタンスのデータによっては発生しないこともある。

**Comment by nakkaa** [comment]
meilisearch側でsortableの設定を追加でしてあげる必要がありそう。
```
curl \
 -X PUT \
 -H 'Authorization: Bearer hoge' \
 'http://localhost:7700/indexes/example---notes/settings/sortable-attributes/' \
  -H 'Content-Type: application/json' \
  --data-binary '[
    "createdAt"
  ]'
```

**Comment by yuba** [comment]
@nakkaa  
手元で再現したのですが、このsortable追加処理はmisskey起動時に行われているようです。  
なのでこの現象は、misskeyを動かしたままmeilisearchを新規起動した場合に起こるのではと思われます。  
対策としては、発生したらmisskey本体を再起動すればと。

**Comment by nakkaa** [comment]
ありがとうございます。
ツール側の不具合というわけではなさそうですね。closeします。

(私はMeilisearchを起動 -> Misskeyを起動 -> aminomeでインデックス追加 で回避できました。)
